// Generates tokens/primitives.json, tokens/semantic.{light,dark}.json, tokens/tokens.json and css/cozy.css
// from tokens/seeds.json + tokens/typography.json. Run: node scripts/build.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { converter, formatHex, clampChroma } from "culori";

const seeds = JSON.parse(readFileSync(new URL("../tokens/seeds.json", import.meta.url)));
const type = JSON.parse(readFileSync(new URL("../tokens/typography.json", import.meta.url)));
const oklch = converter("oklch");

// ---- 1. Primitive color ramps -------------------------------------------------
// Step n ≈ OKLCH lightness n%. Chroma peaks at the base color's lightness and
// tapers toward black and white so the ends stay clean.
// Lightness is eased so step 5 is a deep tinted dark rather than pure black.
const stepL = (step) => 0.08 + (step / 100) * 0.91;
function ramp({ hex, chroma, hue }) {
  const base = oklch(hex);
  if (chroma !== undefined) base.c = chroma;
  if (hue !== undefined) base.h = hue;
  const out = {};
  for (const step of seeds.ramp.steps) {
    const L = stepL(step);
    const spread = step < base.l * 100 ? base.l : 1 - base.l;
    const t = 1 - Math.min(1, Math.abs(L - base.l) / Math.max(spread, 0.01));
    const c = base.c * (0.25 + 0.75 * t);
    out[step] = formatHex(clampChroma({ mode: "oklch", l: L, c, h: base.h ?? 0 }, "oklch", "rgb"));
  }
  return out;
}
const hues = Object.entries(seeds.hues).filter(([k]) => !k.startsWith("$"));
const ramps = Object.fromEntries(hues.map(([k, v]) => [k, ramp(v)]));

const primitives = {
  $description: "Generated by scripts/build.mjs from seeds.json. Do not edit.",
  color: Object.fromEntries(hues.map(([k, v]) => [k, { base: v.hex, label: v.label, ...ramps[k] }])),
  font: Object.fromEntries(Object.entries(seeds.fonts).map(([k, v]) => [k, `"${v.family}", ${v.fallback}`])),
  spacing: Object.fromEntries(Object.entries(seeds.spacing).filter(([k]) => !k.startsWith("$")).map(([k, v]) => [k, `${v}px`])),
  radius: Object.fromEntries(Object.entries(seeds.radius).map(([k, v]) => [k, `${v}px`])),
  breakpoint: Object.fromEntries(Object.entries(seeds.breakpoints).map(([k, v]) => [k, `${v}px`])),
  shadow: Object.fromEntries(Object.entries(seeds.shadows).filter(([k]) => !k.startsWith("$"))),
  blur: Object.fromEntries(Object.entries(seeds.blurs).map(([k, v]) => [k, `${v}px`])),
};

// ---- 2. Semantic roles ---------------------------------------------------------
const R = seeds.roles;
const c = (hue, step) => `{color.${hue}.${step}}`;
function statuses(mode) {
  const light = mode === "light";
  const s = (hue, main) => ({
    main: c(hue, main),
    light: c(hue, light ? 95 : 20),
    foreground: c(hue, light ? 10 : 98),
    dark: c(hue, light ? 30 : 80),
  });
  return {
    success: s(R.success, light ? 80 : 70),
    failure: s(R.failure, light ? 50 : 60),
    warning: s(R.warning, light ? 80 : 70),
    info: s(R.info, light ? 50 : 60),
  };
}
function interactives(mode) {
  const light = mode === "light";
  const n = "neutral";
  return {
    primary: { active: c(R.primary, 50), hover: c(R.primary, 60), inactive: c(R.primary, light ? 95 : 20), disabled: c(n, light ? 80 : 30), text: c(n, 99) },
    secondary: { active: c(R.secondary, light ? 40 : 60), hover: c(R.secondary, light ? 50 : 70), inactive: c(R.secondary, light ? 95 : 20), disabled: c(n, light ? 80 : 30), text: c(n, 99) },
    tertiary: { active: c(n, light ? 30 : 80), hover: c(n, light ? 95 : 35), inactive: c(n, light ? 90 : 30), disabled: c(n, light ? 80 : 35), text: c(n, light ? 10 : 98) },
    accent: { active: c(R.accent, light ? 70 : 70), hover: c(R.accent, light ? 60 : 80), inactive: c(R.accent, light ? 95 : 20), disabled: c(n, light ? 80 : 30), text: c(n, light ? 10 : 10) },
  };
}
function semantic(mode) {
  const light = mode === "light";
  const n = "neutral";
  return {
    $description: `Generated ${mode}-mode roles. Values reference primitives.json.`,
    // Dark mode sits on the softer "cozy black" rather than near-black; layers step lighter from there.
    background: { base: c(n, light ? 98 : 20), layer1: c(n, light ? 99 : 25), layer2: c(n, light ? 95 : 30), layer3: c(n, light ? 90 : 35) },
    text: { primary: c(n, light ? 10 : 98), secondary: c(n, light ? 35 : 80), muted: c(n, light ? 50 : 60), inverse: c(n, light ? 99 : 10), link: c(R.primary, light ? 50 : 70), accent: c(R.accent, light ? 50 : 70) },
    border: { subtle: c(n, light ? 90 : 30), strong: c(n, light ? 70 : 50), focus: c(R.accent, light ? 60 : 70) },
    status: statuses(mode),
    interactive: interactives(mode),
  };
}
const semLight = semantic("light");
const semDark = semantic("dark");

// ---- 3. Combined token file (keeps the original named palette and map colors) -----
const tokens = {
  $description: "cozy design tokens. primitives = generated ramps and scales; light/dark = semantic roles; palette = the original named colors from the Figma guide; map = map style colors.",
  primitives,
  light: semLight,
  dark: semDark,
  typography: type,
  palette: Object.fromEntries(Object.entries(seeds.palette).filter(([k]) => !k.startsWith("$")).map(([k, v]) => [k, v.hex])),
  figma: {
    ...seeds.figma,
    variables: Object.fromEntries(Object.entries(seeds.palette).filter(([k]) => !k.startsWith("$")).map(([k, v]) => [v.figma, `palette.${k}`])),
    textStyles: Object.fromEntries(Object.entries(type).filter(([k]) => !k.startsWith("$")).flatMap(([g, v]) => Object.entries(v.figma ?? {}).map(([size, name]) => [name, `typography.${g}.${size}`]))),
  },
  color: { map: seeds.map },
};

// ---- 4. CSS -----------------------------------------------------------------------
const resolve = (ref) => {
  const m = /^\{color\.(\w+)\.(\d+)\}$/.exec(ref);
  return m ? `var(--color-${m[1]}-${m[2]})` : ref;
};
const kebab = (s) => s.replace(/([a-z])([A-Z])/g, "$1-$2").toLowerCase();
const flat = (obj, path = "", out = []) => {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    const p = path ? `${path}-${kebab(k)}` : kebab(k);
    if (typeof v === "object") flat(v, p, out);
    else out.push(`  --${p}: ${resolve(v)};`);
  }
  return out;
};
const vars = [];
for (const [hue, steps] of Object.entries(ramps)) for (const [s, hex] of Object.entries(steps)) vars.push(`  --color-${hue}-${s}: ${hex};`);
for (const [k, v] of Object.entries(primitives.font)) vars.push(`  --font-${k}: ${v};`);
for (const [k, v] of Object.entries(primitives.spacing)) vars.push(`  --space-${k.replace(".", "_")}: ${v};`);
for (const [k, v] of Object.entries(primitives.radius)) vars.push(`  --radius-${k}: ${v};`);
for (const [k, v] of Object.entries(primitives.shadow)) vars.push(`  --shadow-${k}: ${v};`);
for (const [k, v] of Object.entries(primitives.blur)) vars.push(`  --blur-${k}: ${v};`);
for (const [k, v] of Object.entries(tokens.palette)) vars.push(`  --cozy-${k}: ${v}; /* figma: ${seeds.palette[k].figma} */`);

const typeClasses = [];
const fontVar = (f) => `var(--font-${f})`;
for (const [group, g] of Object.entries(type)) {
  if (group.startsWith("$")) continue;
  const ls = g.letterSpacing ? ` letter-spacing: ${g.letterSpacing}em;` : "";
  const tt = g.transform ? ` text-transform: ${g.transform};` : "";
  for (const [size, rem] of Object.entries(g.sizes)) {
    const fig = (k) => (g.figma?.[k] ? ` /* figma: ${g.figma[k]} */` : "");
    typeClasses.push(`.cozy-${group}-${size} { font: ${g.weight} ${rem}rem/${g.lineHeight} ${fontVar(g.font)};${ls}${tt} }${fig(size)}`);
    if (g.boldWeight) typeClasses.push(`.cozy-${group}-bold-${size} { font: ${g.boldWeight} ${rem}rem/${g.lineHeight} ${fontVar(g.font)};${ls}${tt} }${fig(`bold-${size}`)}`);
    if (g.altWeight && (size === "base" || g.figma?.[`alt-${size}`]))
      typeClasses.push(`.cozy-${group}-alt-${size} { font: ${g.altWeight} ${rem}rem/${g.lineHeight} ${fontVar(g.altFont?.[size] ?? g.font)};${ls}${tt} }${fig(size === "base" ? "alt" : `alt-${size}`)}`);
  }
  for (const [size, rem] of Object.entries(g.mobile ?? {}))
    typeClasses.push(`@media (max-width: ${seeds.breakpoints.md - 1}px) { .cozy-${group}-${size} { font-size: ${rem}rem; } }`);
}

const googleUrl = `https://fonts.googleapis.com/css2?${Object.values(seeds.fonts).map((f) => `family=${f.google}`).join("&")}&display=swap`;
const css = `/* cozy design system. Generated by scripts/build.mjs; edit tokens/seeds.json and tokens/typography.json instead.
 * Fonts (Google Fonts): ${googleUrl}
 * Dark is the default (cozy is a night product). Add data-theme="light" on <html> for light mode.
 */
:root {
${vars.join("\n")}
}

:root, [data-theme="dark"] {
${flat(semDark).join("\n")}
}

[data-theme="light"] {
${flat(semLight).join("\n")}
}

/* Type scale */
${typeClasses.join("\n")}

/* Backwards-compatible aliases used by early cozy-nyc screens */
:root {
  --bg: var(--background-base);
  --text: var(--text-primary);
  --accent: var(--interactive-accent-active);
  --action: var(--interactive-primary-active);
  --alert: var(--status-success-main);
  --foreground: var(--cozy-peach);
}
[data-theme="light"] { --foreground: var(--cozy-deep); }
`;

const w = (p, d) => writeFileSync(new URL(p, import.meta.url), typeof d === "string" ? d : JSON.stringify(d, null, 2) + "\n");
w("../tokens/primitives.json", primitives);
w("../tokens/semantic.light.json", semLight);
w("../tokens/semantic.dark.json", semDark);
w("../tokens/tokens.json", tokens);
w("../css/cozy.css", css);
console.log("built", Object.keys(ramps).length, "ramps,", vars.length, "root vars,", typeClasses.length, "type classes");
